### ISSUE TITLE
Official Hypatia Web and Social Presence

### ISSUE THREAD

**Issue by lillian-lemmer** [hypatia-engine/hypatia#53]
Please construct and document Hypatia's web presence and be sure accounts are accessible to other community managers and, obviously, me! Read the `CODE-OF-CONDUCT.md` and the wiki's [project guidelines](https://github.com/lillian-lemmer/hypatia/wiki/Project-Guidelines). Also, be sure to use the icons/logos from this projects `media/` folder.

Here is the page you'll be referring to and updating for profile information: https://github.com/lillian-lemmer/hypatia/wiki/Profiles

**Comment by lillian-lemmer** [comment]
It doesn't let me assign more than one person. Hrm.

**Comment by ejmr** [comment]
Regarding the project guidelines, specifically about code formatting, have you looked for any tools that could be used to automatically format code to the project's standard style?  Something like `indent` but for Python.  Off the top of my head I don't know of a similar tool for Python, but someone has *probably* created such a program.  If so then it could be setup as part of another Git hook so that commits would automatically have code run through that program to correct and cleanup the formatting.
