### ISSUE TITLE
Contributing on Official Website Wiki vs. In the Repo

### ISSUE THREAD

**Issue by lillian-lemmer** [hypatia-engine/hypatia#76]
So there are two copies of the concept of contributing to Hypatia:

  * Contributing on the wiki: http://hypatia-engine.github.io/wiki/contributing.html
  * "In the repo" meaning: `CONTRIBUTING.md`

I think the best approach may be to simply link to the official website wiki in the repo's contributing.md file?

Alternitively, we could just automatically update the website's wiki page BASED on the CONTRIBUTING.md file... but I feel like the developer's contributor file should be more... plaintext?

What are your thoughts on all of this?

**Comment by ejmr** [comment]
I'm going to update `CONTRIBUTING.md` per our discussion on issue #75, and I believe we can write the file in such a way that it is "plain enough" to be easily read by other developers, while at the same time being formatted in Markdown in such a way that we can use a tool like [Pandoc](http://pandoc.org/) to automatically generate the wiki HTML version of that page from the Markdown document.

So my vote would be to automatically generate the wiki page from the document in the repository.  And personally I like to have as much documentation for projects available *without* requiring an Internet connection, e.g. I was on the road about seven hours today and being able to read all the notes and documentation in the repository was very useful since I had no Internet connection while going down the interstate.

**Comment by alxcenz** [comment]
You wouldn't even need something like Pandoc, the website is completely markdown and the website is autogenerated - all that would be required is submoduling the main repo and symlinking it in. I would say that it might be better to have it on the wiki and then if you want to read the docs just clone the website repo - again, it's all markdown, so you can just read it as is.

**Comment by ejmr** [comment]
> You wouldn't even need something like Pandoc, the website is completely markdown...

True, but the wiki may not always be hosted on GitHub or some site which automatically handles Markdown.  Regardless, I think it's a benefit to be able to easily convert documentation into as many forms and formats as possible.

**Comment by lillian-lemmer** [comment]
What do you think about providing a Python script to handle this? Ideas? Or is this something that'd just be better handled /manually/? As in--there are perhaps some things which are more suited  to being mentioned or illustrated on the website, vs. the `CONTRIBUTING.md` file in the repo.

**Comment by alxcenz** [comment]
I say it's best to keep them separate just for that reason, things are better suited to one or the other and handling them manually is easy 

-----Original Message-----

**Comment by lillian-lemmer** [comment]
@alxcenz I'll trust the webmaster on this one! Closed!
